### ISSUE TITLE
Not working with Home assistant

### ISSUE THREAD

**Issue by rocksolid2018** [homedash/kankun-json#16]
Followed the instruction to the T, however, unable to use the switch with Home assistant. 
I am able to open via browser and turn on and off switch. However, with Home assistant nothing happens.

https://home-assistant.io/components/switch.kankun/

I am missing something? thanks

**Comment by stokito** [comment]
You must manually configure HA so it will connect with Kankun. On HA server open /config/configuration.yaml and add to end:

```
switch:
  platform: kankun
  switches:
    bedroom_heating:
      host: hostname_or_ipaddr
```
Then probably you'll need to restart HA.
Ensure that HA and Kankun are in the same network and sees each other. 
See https://www.home-assistant.io/integrations/kankun/ for details
